id: I24493B4C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:30:39+00:00'
last_modified: '2022-06-07T12:22:33.632069+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6870
  title: ཆར་རླུང་རྗེས་ཀྱི་ཉི་འོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    8C00:
      image_group_id: I3CN6872
      title: Volume 1 of char rlung rjes kyi nyi 'od/
      total_pages: 444
      order: 1
      base_file: 8C00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
