id: P000580
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:12.067280
source_metadata:
  id: bdr:W3CN6870
  title: ཆར་རླུང་རྗེས་ཀྱི་ཉི་འོད།
  author: ''
  volumes:
    c37b67c3a01644e7be0673bff25212b1:
      image_group_id: I3CN6872
      title: Volume 1 of char rlung rjes kyi nyi 'od/
      volume_number: 1
      total_pages: 444
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
